### ISSUE TITLE
对LSD-SLAM应用到手机很感兴趣

### ISSUE THREAD

**Issue by autowo** [luohongcheng/LSD-SLAM_Android#1]
Luohongcheng您好：
       我对LSD-SLAM非常感兴趣，最近也想把算法移植到安卓手机上，做手机在现实场景定位这块的工作，看到您也有这方面的想法，不知道做到什么地步了，看看能否留个联系方式交流一下…

**Comment by luohongcheng** [comment]
你好，我去年移植完了，稳定性不是很好。

**Comment by autowo** [comment]
很厉害啊，不稳定指的是程序崩溃还是执行效率上的问题，或者是计算的相机坐标不稳定？如果我要做这一块的话看您能不能提供点建议，是对lsd_slam_core用NDK生成.so后用jni接口调用，是这个基本思路吗？非常感谢

**Comment by luohongcheng** [comment]
咱们QQ聊吧，1107737691

**Comment by qinchun** [comment]
I guess you did not include the jni folder which should include LSD-SLAM core cpp files, can you take a look at that?
